import 'package:flutter/foundation.dart';

enum AppLanguage { zh, en }

class LanguageProvider extends ChangeNotifier {
  AppLanguage _language = AppLanguage.zh;

  AppLanguage get language => _language;
  bool get isEnglish => _language == AppLanguage.en;

  void setLanguage(AppLanguage language) {
    if (_language == language) return;
    _language = language;
    notifyListeners();
  }

  String t(String key) {
    final table = isEnglish ? _en : _zh;
    return table[key] ?? key;
  }

  static const Map<String, String> _zh = {
    'settings': '設定',
    'language': '語言',
    'chinese': '中文',
    'english': 'English',
    'online': '在線',
    'offline': '離線',
    'switched_online': '已切換到在線模式',
    'switched_offline': '已切換到離線模式',
    'manual_offline_hint': '手動離線模式 - 點擊右上角圖標切換',
    'offline_sync_hint': '離線模式 - 資料將在恢復連線後同步',
    'nav_home': '首頁',
    'nav_report': '上報',
    'nav_history': '記錄',
    'nav_analysis': '分析',
    'nav_followup': '跟進',
    'nav_location': '位置',
    'monitor_title': '建築安全監測',
    'monitor_count_prefix': '共監測',
    'monitor_count_suffix': '個問題報告',
    'pending_sync_suffix': '個待同步',
    'risk_overview': '風險概覽',
    'high_risk': '高風險',
    'medium_risk': '中風險',
    'low_risk': '低風險',
    'pending': '待處理',
    'in_progress': '處理中',
    'resolved': '已解決',
    'quick_report': '快速上報',
    'take_photo': '拍照',
    'take_photo_desc': '開啟相機',
    'gallery': '相簿',
    'select_photo_desc': '選擇照片',
    'take_building_photo': '拍攝建築損壞照片',
    'ai_analyze_category_severity': 'AI 將自動分析問題類別和嚴重程度',
    'ai_analyzing': '🤖 AI 正在分析環境...',
    'identify_safety_risks': '智能識別安全風險',
    'upload_photo': '請先上傳照片',
    'wait_ai_analysis': '請等待 AI 分析完成',
    'no_defect_detected': '目前結果為「未檢測到明顯缺陷 / 證據不足」，不建議提交問題單',
    'ai_complete': '✨ AI 分析完成！',
    'ai_defect_found': '✅ AI 分析完成（已檢測到問題）',
    'ai_no_defect': 'ℹ️ AI 分析完成（未檢測到明顯缺陷）',
    'ai_invalid_result': 'AI 未返回有效結果，請重試',
    'ai_analysis_failed': 'AI 分析失敗: ',
    'submit_success': '✅ 報告已成功提交！正在跳轉到紀錄頁面...',
    'submit_failed': '提交失敗: ',
    'building_safety_issue': '建築安全問題',
    'ai_auto_detect': 'AI 自動檢測',
    'positioning': '定位中（UWB）',
    'ai_no_obvious_defect': '影像證據不足 / 未檢測到缺陷',
    'ai_building_damage': '建築損壞',
    'ai_auto_detect_building_damage': 'AI 自動檢測到建築損壞',
    'history': '歷史記錄',
    'sync_to_cloud': '同步到雲端',
    'synced_success': '已同步',
    'synced_count': '筆報告到雲端',
    'all_updated': '所有報告已是最新',
    'search_report': '搜索報告...',
    'all': '全部',
    'filter_conditions': '篩選條件',
    'status': '狀態',
    'confirm': '確定',
    'no_matching_report': '沒有符合條件的報告',
    'no_report_yet': '暫無報告記錄',
    'risk_distribution': '📊 風險分佈',
    'trend_7days': '📈 近7天趨勢',
    'processing_status': '📋 處理狀態',
    'summary_stats': '📊 彙總統計',
    'high_abbr': '高',
    'medium_abbr': '中',
    'low_abbr': '低',
    'empty_data': '暫無數據',
    'positioning_map': '定位地圖',
    'data_details': '數據詳情',
    'device_settings': '設備設定',
    'error_occurred': '發生錯誤',
    'dismiss': '關閉',
  };

  static const Map<String, String> _en = {
    'settings': 'Settings',
    'language': 'Language',
    'chinese': '中文',
    'english': 'English',
    'online': 'Online',
    'offline': 'Offline',
    'switched_online': 'Switched to online mode',
    'switched_offline': 'Switched to offline mode',
    'manual_offline_hint': 'Manual offline mode - tap top-right icon to switch',
    'offline_sync_hint':
        'Offline mode - data will sync when connection resumes',
    'nav_home': 'Home',
    'nav_report': 'Report',
    'nav_history': 'History',
    'nav_analysis': 'Analysis',
    'nav_followup': 'Follow-up',
    'nav_location': 'Location',
    'monitor_title': 'Building Safety Monitoring',
    'monitor_count_prefix': 'Monitoring',
    'monitor_count_suffix': 'issue reports',
    'pending_sync_suffix': 'pending sync',
    'risk_overview': 'Risk Overview',
    'high_risk': 'High Risk',
    'medium_risk': 'Medium Risk',
    'low_risk': 'Low Risk',
    'pending': 'Pending',
    'in_progress': 'In Progress',
    'resolved': 'Resolved',
    'quick_report': 'Quick Report',
    'take_photo': 'Take Photo',
    'take_photo_desc': 'Open Camera',
    'gallery': 'Gallery',
    'select_photo_desc': 'Select Photo',
    'take_building_photo': 'Take Photo of Building Damage',
    'ai_analyze_category_severity':
        'AI will automatically analyze issue category and severity',
    'ai_analyzing': '🤖 AI is analyzing environment...',
    'identify_safety_risks': 'Smart identification of safety risks',
    'upload_photo': 'Please upload a photo first',
    'wait_ai_analysis': 'Please wait for AI analysis to complete',
    'no_defect_detected':
        'Current result: "No obvious defects detected / insufficient evidence", not recommended to submit',
    'ai_complete': '✨ AI analysis complete!',
    'ai_defect_found': '✅ AI analysis complete (problem detected)',
    'ai_no_defect': 'ℹ️ AI analysis complete (no obvious defects)',
    'ai_invalid_result': 'AI did not return valid result, please retry',
    'ai_analysis_failed': 'AI analysis failed: ',
    'submit_success':
        '✅ Report submitted successfully! Redirecting to history...',
    'submit_failed': 'Submit failed: ',
    'building_safety_issue': 'Building Safety Issue',
    'ai_auto_detect': 'AI Auto Detection',
    'positioning': 'Positioning (UWB)',
    'ai_no_obvious_defect': 'Insufficient image evidence / No defects detected',
    'ai_building_damage': 'Building Damage',
    'ai_auto_detect_building_damage':
        'AI automatically detected building damage',
    'history': 'History',
    'sync_to_cloud': 'Sync to Cloud',
    'synced_success': 'Synced',
    'synced_count': 'reports to cloud',
    'all_updated': 'All reports are up to date',
    'search_report': 'Search reports...',
    'all': 'All',
    'filter_conditions': 'Filter Conditions',
    'status': 'Status',
    'confirm': 'Confirm',
    'no_matching_report': 'No matching reports',
    'no_report_yet': 'No reports yet',
    'risk_distribution': '📊 Risk Distribution',
    'trend_7days': '📈 7-Day Trend',
    'processing_status': '📋 Processing Status',
    'summary_stats': '📊 Summary Statistics',
    'high_abbr': 'H',
    'medium_abbr': 'M',
    'low_abbr': 'L',
    'empty_data': 'No data yet',
    'positioning_map': 'Positioning Map',
    'data_details': 'Data Details',
    'device_settings': 'Device Settings',
    'error_occurred': 'Error occurred',
    'dismiss': 'Dismiss',
  };
}
