[build]
  command = """
if [ ! -d \"$HOME/flutter-sdk\" ]; then
  git clone https://github.com/flutter/flutter.git --depth 1 -b stable \"$HOME/flutter-sdk\"
fi
export PATH=\"$HOME/flutter-sdk/bin:$PATH\"
flutter --version
flutter pub get
flutter build web --release --target lib/main_web.dart
"""
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
